export const stateTree = {
    followers: [
        {id:1,  name: "Mark Doe",    status:false, image:"https://bootdey.com/img/Content/avatar/avatar7.png",  username: "Mark Doe"},
        {id:2,  name: "Clark Man",   status:false, image:"https://bootdey.com/img/Content/avatar/avatar6.png",  username: "Clark Man"} ,
        {id:3,  name: "Jaden Boor",  status:false, image:"https://bootdey.com/img/Content/avatar/avatar5.png",  username: "Jaden Boor"} ,
        {id:4,  name: "Srick Tree",  status:false, image:"https://bootdey.com/img/Content/avatar/avatar4.png",  username: "Srick Tree"} ,
        {id:5,  name: "Erick Doe",   status:false, image:"https://bootdey.com/img/Content/avatar/avatar3.png",  username: "Erick Doe"} ,
        {id:6,  name: "Francis Doe", status:false, image:"https://bootdey.com/img/Content/avatar/avatar2.png",  username: "Francis Doe"} ,
        {id:7,  name: "Francis Doe", status:false, image:"https://bootdey.com/img/Content/avatar/avatar2.png",  username: "Francis Doe"} ,
        {id:8,  name: "Matilde Doe", status:false, image:"https://bootdey.com/img/Content/avatar/avatar1.png",  username: "Matilde Doe"} ,
        {id:9,  name: "John Doe",    status:false, image:"https://bootdey.com/img/Content/avatar/avatar4.png",  username: "John Doe"} ,
        {id:10, name: "Fermod Doe",  status:false, image:"https://bootdey.com/img/Content/avatar/avatar7.png",  username: "Fermod Doe"} ,
        {id:11, name: "Danny Doe",   status:false, image:"https://bootdey.com/img/Content/avatar/avatar1.png",  username: "Danny Doe"},
        {id:12,  name: "Clark Man",   status:false, image:"https://bootdey.com/img/Content/avatar/avatar6.png",  username: "Clark Man"} ,
        {id:13,  name: "Jaden Boor",  status:false, image:"https://bootdey.com/img/Content/avatar/avatar5.png",  username: "Jaden Boor"} ,
        {id:14,  name: "Srick Tree",  status:false, image:"https://bootdey.com/img/Content/avatar/avatar4.png",  username: "Srick Tree"} ,
        {id:15,  name: "Erick Doe",   status:false, image:"https://bootdey.com/img/Content/avatar/avatar3.png",  username: "Erick Doe"} ,
        {id:16,  name: "Francis Doe", status:false, image:"https://bootdey.com/img/Content/avatar/avatar2.png",  username: "Francis Doe"} ,
        {id:17,  name: "Matilde Doe", status:false, image:"https://bootdey.com/img/Content/avatar/avatar1.png",  username: "Matilde Doe"} ,
        {id:18,  name: "John Doe",    status:false, image:"https://bootdey.com/img/Content/avatar/avatar4.png",  username: "John Doe"} ,
        {id:19,  name: "John Doe",    status:false, image:"https://bootdey.com/img/Content/avatar/avatar4.png",  username: "John Doe"} ,
        {id:20, name: "Fermod Doe",  status:false, image:"https://bootdey.com/img/Content/avatar/avatar7.png",  username: "Fermod Doe"} ,
      ],
    numColumns:2,
    data: [
      {id:1,  image:"https://bootdey.com/img/Content/avatar/avatar1.png"}, 
      {id:2,  image:"https://bootdey.com/img/Content/avatar/avatar2.png"}, 
      {id:3,  image:"https://bootdey.com/img/Content/avatar/avatar3.png"}, 
      {id:4,  image:"https://bootdey.com/img/Content/avatar/avatar4.png"}, 
      {id:5,  image:"https://bootdey.com/img/Content/avatar/avatar5.png"}, 
      {id:6,  image:"https://bootdey.com/img/Content/avatar/avatar6.png"}, 
      {id:7,  image:"https://bootdey.com/img/Content/avatar/avatar7.png"}, 
      {id:8,  image:"https://bootdey.com/img/Content/avatar/avatar1.png"}, 
      {id:9,  image:"https://bootdey.com/img/Content/avatar/avatar2.png"}, 
      {id:10, image:"https://bootdey.com/img/Content/avatar/avatar3.png"},
      {id:11,  image:"https://bootdey.com/img/Content/avatar/avatar6.png"}, 
      {id:12,  image:"https://bootdey.com/img/Content/avatar/avatar4.png"}, 
      {id:13,  image:"https://bootdey.com/img/Content/avatar/avatar2.png"}, 
      {id:14,  image:"https://bootdey.com/img/Content/avatar/avatar4.png"}, 
      {id:15,  image:"https://bootdey.com/img/Content/avatar/avatar5.png"}, 
      {id:16,  image:"https://bootdey.com/img/Content/avatar/avatar6.png"}, 
      {id:17,  image:"https://bootdey.com/img/Content/avatar/avatar7.png"}, 
      {id:18,  image:"https://bootdey.com/img/Content/avatar/avatar1.png"}, 
      {id:19,  image:"https://bootdey.com/img/Content/avatar/avatar2.png"}, 
      {id:20, image:"https://bootdey.com/img/Content/avatar/avatar3.png"},
    ]
}